### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by ManBug69** [DeltaNedas/dev-mode#1]
Hey! this seems like a great addition, however for newbies to scripts like me it would be nice to have a repository of pre made commands for console, is there anything like this available?

**Comment by DeltaNedas** [comment]
if you aren't a mod dev you probably don't need it.
It's like getting a raspberry pi just to have it, you should know what to do going in.

**Comment by ManBug69** [comment]
Thank you! Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: DeltaNedas <notifications@github.com> Date: 8/26/20  7:42 PM  (GMT-05:00) To: DeltaNedas/dev-mode <dev-mode@noreply.github.com> Cc: ManBug69 <alexflannery96@gmail.com>, Author <author@noreply.github.com> Subject: Re: [DeltaNedas/dev-mode] Instructions (#1) 
if you aren't a mod dev you probably don't need it.
It's like getting a raspberry pi just to have it, you should know what to do going in.

**Comment by ASFRedstone** [comment]
Hey, how do I even use this?

**Comment by DeltaNedas** [comment]
read the mod description
