### ISSUE TITLE
how

### ISSUE THREAD

**Issue by yesC48** [DeltaNedas/dev-mode#13]
mod version: i have no idea
client version: 126.2
issue: while i was playing with dev commands such as:

UnitTypes.gamma.weapons.add(UnitTypes.[unit here].weapons.get([number of the weapon, starting from 0]))
there is this bug that causes this to happen in servers:
![Screenshot_20210623-152924](https://user-images.githubusercontent.com/74853156/123056106-24c44900-d439-11eb-9fa9-26c1963fb307.png)
this is in a russian server ^^
![Screenshot_20210623-153234](https://user-images.githubusercontent.com/74853156/123056161-360d5580-d439-11eb-84e0-e356291e98d8.png)
also another server ^^
![Screenshot_20210623-152147](https://user-images.githubusercontent.com/74853156/123056242-48878f00-d439-11eb-9310-e353448e417f.png)
me messing with the mod in real time ^^

[X] i checked that there are no more issues containing the same problem

**Comment by Cerulity32K** [comment]
Not sure, but maybe the console tries to call /js to update everyone's clients.
This executes pure JavaScript, and giving unspeakable health and damage to a core unit should stay to admins only.

**Comment by DeltaNedas** [comment]
the console is clientside only and doesnt try to execute commands, some other mod must be doing that
