### ISSUE TITLE
Command doesn't appear

### ISSUE THREAD

**Issue by ghost** [deltanedas/dev-mode#19]
![Screenshot_Mindustry_20220727-210540](https://user-images.githubusercontent.com/105666518/181269295-c4d63084-8828-42e4-92f6-636813c33159.png)

I have installed ui-lib and devmode, but only command button appears, the screen to write code doesn't appear. I'm playing on version 136.

**Comment by deltanedas** [comment]
aware of issue, dont know why it doesnt work

**Comment by deltanedas** [comment]
pretty sure this mod isnt needed anymore since theres a built in option

**Comment by Zapidipodot** [comment]
not in mobile/android tho
