### ISSUE TITLE
Add a proper command list

### ISSUE THREAD

**Issue by Erisfiregamer1** [DeltaNedas/dev-mode#4]
There isnt a proper list of commands and how to use them. Maybe add one?

**Comment by Erisfiregamer1** [comment]
This is mainly because a whole load of potential lies here, if people knew how to use it.

**Comment by Erisfiregamer1** [comment]
Here are some I know:
UnitTypes.[unit].[thing to modify, like speed]=[value]
And some others.
haha duo machine gun go BRRRRRRRRRRR

**Comment by DeltaNedas** [comment]
noob

**Comment by Colonizor48** [comment]
For some reason trying to do the same thing with blocks returns an error. Idk i might just be bad.
Typing somthing like ItemTurret.duo.reload = NaN just outputs an error saying that the class doesnt exist.  And i know it doesnt have anything to do with NaN

**Comment by Colonizor48** [comment]
As in class i mean duo. But checking the games code there is clerely an object named duo with the class ItemTurret.

**Comment by firstcreator48** [comment]
> For some reason trying to do the same thing with blocks returns an error. Idk i might just be bad.
> Typing somthing like ItemTurret.duo.reload = NaN just outputs an error saying that the class doesnt exist. And i know it doesnt have anything to do with NaN

NaN means not a number so it returns it is not a type of class
