### ISSUE TITLE
the - character is treated as a space

### ISSUE THREAD

**Issue by Colonizor48** [DeltaNedas/dev-mode#7]
Title. This could just be me being a noob but idk

**Comment by Colonizor48** [comment]
also for some reason i cant change the properties of ItemTurret.duo Dispite ItemTurret being a public class to my knowlage. Im not exactly the most familiar with object oriented programing. But i should probably be able to change its properties

**Comment by DeltaNedas** [comment]
???
- is used for binary subtraction and unary negation
