### ISSUE TITLE
This isint really an issue but i need help

### ISSUE THREAD

**Issue by notMEEPoffaith** [DeltaNedas/dev-mode#9]
how to make conveyors faster

**Comment by DeltaNedas** [comment]
![Screenshot_02:20:36](https://user-images.githubusercontent.com/39013340/107596483-bd3af900-6c0f-11eb-9d2f-af6f53798aa6.png)
![Screenshot_02:20:40](https://user-images.githubusercontent.com/39013340/107596491-be6c2600-6c0f-11eb-9703-60534bab3a25.png)

**Comment by liuxilu** [comment]
I wonder where should these questions be asked.

**Comment by DeltaNedas** [comment]
nowhere, if you dont know how to use javascript simply dont install this mod
